<a href="https://colab.research.google.com/github/Gabrieldacostamachado/phyton/blob/main/Estrutura_de_dados_em_phyton_materia_2_objetos_sequencia%2C_tuplas%2C_listas%2C_array_numpy%2C_mapping%2C_set_e_exercicio_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Aula unidade 2 Phyton,
#Objetos do tipo de sequencia

texto = "Explorando a diversidade de linguagens de programação com Python."
#len = comprimento do ()
print(f"Tamanho do texto = {len(texto)}")
#in = True caso encontre '' no ()
print(f"Python in texto = {'Python' in texto}")
#texto.count = Conta a quantidade de ('') no código mencionado
print(f"Quantidade de E no texto = {texto.count('e')}")
#:5 = Informa as primeiras letras da string selecionada {[:5]}
print(f"As 5 primeiras letras são: {texto[:5]}")



Tamanho do texto = 65
Python in texto = True
Quantidade de E no texto = 5
As 5 primeiras letras são: Explo


In [ ]:
#Informa o elemento selecionado, começando sempre em 0, e terminando em n-1 Ex. 65 - 1 = 64
texto[64]

'.'

In [ ]:
#Listas

cores = ['Vermelho', 'Amarelo', 'Azul', 'Branco', 'Preto']
for cor in cores:
    print(f"Posição = {cores.index(cor)}, cor = {cor}")

Posição = 0, cor = Vermelho
Posição = 1, cor = Amarelo
Posição = 2, cor = Azul
Posição = 3, cor = Branco
Posição = 4, cor = Preto


In [ ]:
#listcomps = Listas criadas a apartir de uma lista antiga, com as informações esejadas]
linguagens = ['Javascript', 'Python', 'C#', 'Java', 'C++', 'Swift', 'C', 'Go', 'Kothlin']
print("Antes da listcomp = ", linguagens)
#A lista linguagens, a baixo sofre uma alteração passando todas as letras para minúsculo, criando uma nova lista com base na anterior
linguagens = {item.lower() for item in linguagens}
# O \n representa que o resultado do código, ira oara uma nova linha.
print("\nDepois da listcomp = ", linguagens)

Antes da listcomp =  ['Javascript', 'Python', 'C#', 'Java', 'C++', 'Swift', 'C', 'Go', 'Kothlin']

Depois da listcomp =  {'javascript', 'kothlin', 'java', 'python', 'c#', 'c', 'go', 'c++', 'swift'}


In [ ]:
#Função map
#Aplica a função em todo a sequencia
#map(função,sequencia)

#Em listas, numeros não vao entre '', somente as strings ex 'verde', 'amarelo'
precos_em_dolares = [100, 50, 75, 120]
taxa_de_cambio = 5.25
precos_em_reais = list(map(lambda x: x * taxa_de_cambio, precos_em_dolares))
print(precos_em_reais)

[525.0, 262.5, 393.75, 630.0]


In [ ]:
#Função filter
#Filtra os elementos de uma sequencia com base em uma função teste (retorna true or false)
#filter(funcao_teste, sequencia)

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
numeros_pares = list(filter(lambda x: x % 2 == 0, numeros))
print(numeros_pares)


[2, 4, 6, 8, 10]


In [ ]:
#Tuplas = um tipo de lista, imutável, onde não podem haver alterações

vogais = ('a', 'e', 'i', 'o', 'u')
print(f'Tipo do objeto vogais ={type(vogais)}')
for p, x in enumerate(vogais):
    print(f'Posição ={p}, valor = {x}')

Tipo do objeto vogais =<class 'tuple'>
Posição =0, valor = a
Posição =1, valor = e
Posição =2, valor = i
Posição =3, valor = o
Posição =4, valor = u


In [ ]:
# Exercício Lista de convidados e confirmdos para evento, lembrando quem deverá ser convidado novamente

#Tupla lista de convidados
convidados = ('Rogério', 'Ana', 'Beatriz', 'Cesar', 'Lucas', 'Denise', 'Mario', 'Maria')
#Lista de confirmados
confirmados =('Beatriz', 'Cesar', 'Maria')
#Identificar quem ainda não confirmou
nao_confirmados = [convidado for convidado in convidados if convidado not in confirmados]

#exibir os convidados que ainda não foram confirmados
print("convidados que ainda não confirmaram:")
for pessoa in nao_confirmados:
    print(pessoa)
#Enviar lembrete para os não confirmados
print("\nEnviar lembrete para os convidados ainda não confirmados")

convidados que ainda não confirmaram:
Rogério
Ana
Lucas
Denise
Mario

Enviar lembrete para os convidados ainda não confirmados


In [1]:
# Estruturas de dados em Phyton pt 2
#Objetos tipo SET
#add(), in e remove()
#Criada uma lista vazia, que depois ira ter um elemento novo adicionado por código
#Lista vazia
meu_conjunto = set()

meu_conjunto


set()

In [8]:
#adcionando elementos ao conjunto
meu_conjunto.add(10)
meu_conjunto.add(20)
meu_conjunto.add(30)

#imprimindo o conjunto com os novos elementos
print("Conjunto após adicionar elementos :", meu_conjunto)

Conjunto após adicionar elementos : {10, 20, 30}


In [9]:
#Verificando se o elemento esta no conjunto
elemento = 20
if elemento in meu_conjunto:
    print(f"{elemento} esta no conjunto")
else:
    print(f"{elemento} não esta no conjunto")


20 esta no conjunto


In [10]:
#Removendo elemento do conjunto
meu_conjunto.remove(20)
#Imprimindo novo conjunto atualizado
print("Conjunto pós remover elemento :", meu_conjunto)

Conjunto pós remover elemento : {10, 30}


In [16]:
#Ex 1. Criando um dicionario vazio, seguindo de atribuições de chaves e valores

dict_1 ={}

dict_1['nome'] = "Maria"
dict_1['idade'] = 25

#Ex 2. Criação de um dicionario com pares chave valor
dict_2 = {'nome': 'Maria', 'idade': 25}

#Ex 3. Criação de um dicionario com uma lista de tuplas representando pares chaves: valor
dict_3 = dict([('nome', "Maria"), ('idade', 25)])

#Ex 4. Criando um dicionario usando a função built-in zip() e duas listas, uma para as chaves e outra para valor
dict_4 = dict(zip(['nome', 'idade'], ["Maria", 25]))

#Teste se todas as execuções retornam objetos iguais
print(dict_1 == dict_2 == dict_3 == dict_4) #Deve imprimir true
print(dict_1)


True
{'nome': 'Maria', 'idade': 25}


In [2]:
#Importe uma bibliotreca numpy
import numpy as np

#Crie um array numpy de numeros inteiros
my_array = np.array([1, 2, 3, 4, 5])



array([1, 2, 3, 4, 5])

In [7]:
#Imprima o array
print("array original:")
print(my_array)

array original:
[1 2 3 4 5]


In [8]:
#realize operações matematicas com o array
squared_array = my_array ** 2 #Eleva ao quadrado
sum_of_elements = np.sum(my_array) #Calcula a soma de todos os elementos

In [10]:
#Imprima os resultados
print("\narray ao quadrado:")
print(squared_array)
print("\nsoma dos elementos:")
print(sum_of_elements)


array ao quadrado:
[ 1  4  9 16 25]

soma dos elementos:
15


In [14]:
#Acesse os elementos do array
element_at_index_2 = my_array[2] #Acessa o elemento indice 2 (A contagem sempre começa do 0 em diante ex.: 0,1,2,3,4,...)
print("\nElemento no indice 2:", element_at_index_2)


Elemento no indice 2: 3


In [8]:
#Exercicio
# Estamos gerenciando um eventos com participantes de diferentes regiões do mundo, cada participante forneceu informações como localização, afiliação, instituição de pesquisa e área de interesse
#vamos analisar a distribuição Geografica, áreas de interesses e afiliações destes usuarios

#Importe as bibliotecas necessárias
import numpy as np
#Dados dos participantes
participantes = [
    {
        "nome": "Alice",
        "localizacao": "Brasil",
        "interesses": ["Ciência de Dados", "Analise de sistemas"],
        "afiliacao": "Universidade Anhanguera"
    },
    {
        "nome": "Lucas",
        "localizacao": "China",
        "interesses": ["Analise de sistemas", "Python"],
        "afiliacao": "Universidade Cesuca"
    },
    {
        "nome": "Jonas",
        "localizacao": "Uruguai",
        "interesses": ["Ciência de Dados", "Analise de sistemas"],
        "afiliacao": "Universidade Uniasselvi"
    },
    {
        "nome": "Gabriel",
        "localizacao": "Brasil",
        "interesses": ["Analise de sistemas", "Python"],
        "afiliacao": "Universidade Anhanguera"
    },
    {
        "nome": "João",
        "localizacao": "Alemanha",
        "interesses": ["Analise de sistemas", "C++"],
        "afiliacao": "Universidade Anhanguera"
    }
]

#Usando sets para identificar diferentes regiões dos particiantes
regioes = set(participante["localizacao"] for participante in participantes)

#Usando dicionario para categorizar asafiliações
afiliacoes = {}
for participante in participantes:
    afiliacao = participante["afiliacao"]
    if afiliacao not in afiliacoes:
        afiliacoes[afiliacao] = []
    afiliacoes[afiliacao].append(participante["nome"])

#Usando numpy para analisar áreas de interesse

areas_de_interesse = np.array([interesse for participante in participantes for interesse in participante["interesses"]])
interesses_unicos, contagem = np.unique(areas_de_interesse, return_counts=True)

area_mais_popular = interesses_unicos[np.argmax(contagem)]

#Resultados
print("Regiões dos participantes:", regioes)
print("Afiliação dos participantes:")
for afiliacao, nomes in afiliacoes.items():
   print(f"{afiliacao}: {', '. join(nomes)}")
print("Área de interesse mais popular:", area_mais_popular)


Regiões dos participantes: {'Alemanha', 'Uruguai', 'Brasil', 'China'}
Afiliação dos participantes:
Universidade Anhanguera: Alice, Gabriel, João
Universidade Cesuca: Lucas
Universidade Uniasselvi: Jonas
Área de interesse mais popular: Analise de sistemas
